require("qilin.plugins-setup")
require("qilin.core.options")
require("qilin.core.keymaps")
require("qilin.core.colorscheme")
require("qilin.plugins.comment")
require("qilin.plugins.nvim-tree")
require("qilin.plugins.lualine")
require("qilin.plugins.telescope")
require("qilin.plugins.nvim-cmp")
require("qilin.plugins.lsp.mason")
require("qilin.plugins.lsp.lspsaga")
require("qilin.plugins.lsp.lspconfig")
require("qilin.plugins.lsp.null-ls")
require("qilin.plugins.autopairs")
-- require("qilin.plugins.treesitter")
require("qilin.plugins.gitsigns")
